# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RackoMain.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from gui.customLabel import CardLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(716, 739)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(716, 739))
        MainWindow.setMaximumSize(QtCore.QSize(716, 739))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutMain = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayoutMain.setObjectName("gridLayoutMain")

        self.settingLayout = QtWidgets.QGridLayout()
        self.settingLayout.setObjectName("settingLayout")
        self.headingSetup = QtWidgets.QLabel(self.centralwidget)
        self.headingSetup.setObjectName("headingSetup")
        self.settingLayout.addWidget(self.headingSetup, 0, 0, 1, 3)
        self.requirePlayer2 = QtWidgets.QComboBox(self.centralwidget)
        self.requirePlayer2.setObjectName("requirePlayer2")
        self.requirePlayer2.addItem("")
        self.requirePlayer2.addItem("")
        self.requirePlayer2.addItem("")
        self.settingLayout.addWidget(self.requirePlayer2, 1, 0, 1, 1)
        self.optionPlayer3 = QtWidgets.QComboBox(self.centralwidget)
        self.optionPlayer3.setObjectName("optionPlayer3")
        self.optionPlayer3.addItem("")
        self.optionPlayer3.addItem("")
        self.optionPlayer3.addItem("")
        self.optionPlayer3.addItem("")
        self.settingLayout.addWidget(self.optionPlayer3, 1, 1, 1, 1)
        self.optionPlayer4 = QtWidgets.QComboBox(self.centralwidget)
        self.optionPlayer4.setObjectName("optionPlayer4")
        self.optionPlayer4.addItem("")
        self.optionPlayer4.addItem("")
        self.optionPlayer4.addItem("")
        self.optionPlayer4.addItem("")
        self.optionPlayer4.addItem("")
        self.settingLayout.addWidget(self.optionPlayer4, 1, 2, 1, 1)
        self.actionButton = QtWidgets.QPushButton(self.centralwidget)
        self.actionButton.setObjectName("actionButton")
        self.settingLayout.addWidget(self.actionButton, 0, 3, 1, 1)
        self.optionView = QtWidgets.QRadioButton(self.centralwidget)
        self.optionView.setObjectName("optionView")
        self.settingLayout.addWidget(self.optionView, 1, 3, 1, 1)
        self.gridLayoutMain.addLayout(self.settingLayout, 0, 2, 1, 3)        
        
        self.headingGame = QtWidgets.QLabel(self.centralwidget)
        self.headingGame.setMinimumSize(QtCore.QSize(0, 20))
        self.headingGame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingGame.setAlignment(QtCore.Qt.AlignCenter)
        self.headingGame.setObjectName("headingGame")
        self.gridLayoutMain.addWidget(self.headingGame, 5, 2, 1, 3)
        self.spacingL = QtWidgets.QLabel(self.centralwidget)
        self.spacingL.setMinimumSize(QtCore.QSize(20, 0))
        self.spacingL.setMaximumSize(QtCore.QSize(20, 16777215))
        self.spacingL.setText("")
        self.spacingL.setObjectName("spacingL")
        self.gridLayoutMain.addWidget(self.spacingL, 5, 1, 6, 1)
        self.spacingR = QtWidgets.QLabel(self.centralwidget)
        self.spacingR.setMinimumSize(QtCore.QSize(20, 0))
        self.spacingR.setMaximumSize(QtCore.QSize(20, 16777215))
        self.spacingR.setText("")
        self.spacingR.setObjectName("spacingR")
        self.gridLayoutMain.addWidget(self.spacingR, 5, 5, 6, 1)
        self.headingDrawPile = QtWidgets.QLabel(self.centralwidget)
        self.headingDrawPile.setMinimumSize(QtCore.QSize(0, 20))
        self.headingDrawPile.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingDrawPile.setAlignment(QtCore.Qt.AlignCenter)
        self.headingDrawPile.setObjectName("headingDrawPile")
        self.gridLayoutMain.addWidget(self.headingDrawPile, 6, 2, 1, 1)
        self.imgDrawPile = CardLabel(self.centralwidget)
        self.imgDrawPile.setFrameShape(QtWidgets.QFrame.Box)
        self.imgDrawPile.setLineWidth(1)
        self.imgDrawPile.setPixmap(QtGui.QPixmap("images/backcard.png"))
        self.imgDrawPile.setScaledContents(True)
        self.imgDrawPile.setObjectName("imgDrawPile")
        self.gridLayoutMain.addWidget(self.imgDrawPile, 7, 2, 1, 1)
        self.headingDiscardPile = QtWidgets.QLabel(self.centralwidget)
        self.headingDiscardPile.setMinimumSize(QtCore.QSize(0, 20))
        self.headingDiscardPile.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingDiscardPile.setAlignment(QtCore.Qt.AlignCenter)
        self.headingDiscardPile.setObjectName("headingDiscardPile")
        self.gridLayoutMain.addWidget(self.headingDiscardPile, 6, 4, 1, 1)
        self.imgDiscardPile = QtWidgets.QLabel(self.centralwidget)
        self.imgDiscardPile.setFrameShape(QtWidgets.QFrame.Box)
        self.imgDiscardPile.setLineWidth(1)
        self.imgDiscardPile.setPixmap(QtGui.QPixmap("images/empty.png"))
        self.imgDiscardPile.setScaledContents(True)
        self.imgDiscardPile.setObjectName("imgDiscardPile")
        self.gridLayoutMain.addWidget(self.imgDiscardPile, 7, 4, 1, 1)
        self.statusGame = QtWidgets.QTextBrowser(self.centralwidget)
        self.statusGame.setMinimumSize(QtCore.QSize(515, 125))
        self.statusGame.setMaximumSize(QtCore.QSize(515, 125))
        self.statusGame.setObjectName("statusGame")
        self.gridLayoutMain.addWidget(self.statusGame, 13, 2, 1, 3)

        self.headingPlayer1 = QtWidgets.QLabel(self.centralwidget)
        self.headingPlayer1.setMinimumSize(QtCore.QSize(0, 20))
        self.headingPlayer1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingPlayer1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.headingPlayer1.setObjectName("headingPlayer1")
        self.gridLayoutMain.addWidget(self.headingPlayer1, 1, 0, 1, 1)
        self.scorePlayer1 = QtWidgets.QLabel(self.centralwidget)
        self.scorePlayer1.setAlignment(QtCore.Qt.AlignCenter)
        self.scorePlayer1.setObjectName("scorePlayer1")
        self.gridLayoutMain.addWidget(self.scorePlayer1, 2, 0, 1, 1)
        self.headingPlayer2 = QtWidgets.QLabel(self.centralwidget)
        self.headingPlayer2.setMinimumSize(QtCore.QSize(0, 20))
        self.headingPlayer2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingPlayer2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.headingPlayer2.setObjectName("headingPlayer2")
        self.gridLayoutMain.addWidget(self.headingPlayer2, 1, 2, 1, 3)
        self.scorePlayer2 = QtWidgets.QLabel(self.centralwidget)
        self.scorePlayer2.setAlignment(QtCore.Qt.AlignCenter)
        self.scorePlayer2.setObjectName("scorePlayer2")
        self.gridLayoutMain.addWidget(self.scorePlayer2, 2, 2, 1, 3)
        self.headingPlayer3 = QtWidgets.QLabel(self.centralwidget)
        self.headingPlayer3.setMinimumSize(QtCore.QSize(0, 20))
        self.headingPlayer3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingPlayer3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.headingPlayer3.setObjectName("headingPlayer3")
        self.gridLayoutMain.addWidget(self.headingPlayer3, 1, 6, 1, 1)
        self.scorePlayer3 = QtWidgets.QLabel(self.centralwidget)
        self.scorePlayer3.setAlignment(QtCore.Qt.AlignCenter)
        self.scorePlayer3.setObjectName("scorePlayer3")
        self.gridLayoutMain.addWidget(self.scorePlayer3, 2, 6, 1, 1)
        self.headingPlayer4 = QtWidgets.QLabel(self.centralwidget)
        self.headingPlayer4.setMinimumSize(QtCore.QSize(0, 20))
        self.headingPlayer4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.headingPlayer4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.headingPlayer4.setObjectName("headingPlayer4")
        self.gridLayoutMain.addWidget(self.headingPlayer4, 9, 2, 1, 3)
        self.scorePlayer4 = QtWidgets.QLabel(self.centralwidget)
        self.scorePlayer4.setAlignment(QtCore.Qt.AlignCenter)
        self.scorePlayer4.setObjectName("scorePlayer4")
        self.gridLayoutMain.addWidget(self.scorePlayer4, 10, 2, 1, 3)
         
        font = QtGui.QFont()
        font.setFamily("Superclarendon")
        font.setPointSize(24)
        
        self.player1lLayout = QtWidgets.QVBoxLayout()
        self.player1lLayout.setObjectName("player1lLayout")
        self.player1Slot10 = CardLabel(self.centralwidget)
        self.player1Slot10.setSizePolicy(sizePolicy)
        self.player1Slot10.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot10.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot10.setFont(font)
        self.player1Slot10.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot10.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot10.setObjectName("player1Slot10")
        self.player1lLayout.addWidget(self.player1Slot10)
        self.player1Slot09 = CardLabel(self.centralwidget)
        self.player1Slot09.setSizePolicy(sizePolicy)
        self.player1Slot09.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot09.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot09.setFont(font)
        self.player1Slot09.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot09.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot09.setObjectName("player1Slot09")
        self.player1lLayout.addWidget(self.player1Slot09)
        self.player1Slot08 = CardLabel(self.centralwidget)
        self.player1Slot08.setSizePolicy(sizePolicy)
        self.player1Slot08.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot08.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot08.setFont(font)
        self.player1Slot08.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot08.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot08.setObjectName("player1Slot08")
        self.player1lLayout.addWidget(self.player1Slot08)
        self.player1Slot07 = CardLabel(self.centralwidget)
        self.player1Slot07.setSizePolicy(sizePolicy)
        self.player1Slot07.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot07.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot07.setFont(font)
        self.player1Slot07.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot07.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot07.setObjectName("player1Slot07")
        self.player1lLayout.addWidget(self.player1Slot07)
        self.player1Slot06 = CardLabel(self.centralwidget)
        self.player1Slot06.setSizePolicy(sizePolicy)
        self.player1Slot06.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot06.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot06.setFont(font)
        self.player1Slot06.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot06.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot06.setObjectName("player1Slot06")
        self.player1lLayout.addWidget(self.player1Slot06)
        self.player1Slot05 = CardLabel(self.centralwidget)
        self.player1Slot05.setSizePolicy(sizePolicy)
        self.player1Slot05.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot05.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot05.setFont(font)
        self.player1Slot05.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot05.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot05.setObjectName("player1Slot05")
        self.player1lLayout.addWidget(self.player1Slot05)
        self.player1Slot04 = CardLabel(self.centralwidget)
        self.player1Slot04.setSizePolicy(sizePolicy)
        self.player1Slot04.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot04.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot04.setFont(font)
        self.player1Slot04.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot04.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot04.setObjectName("player1Slot04")
        self.player1lLayout.addWidget(self.player1Slot04)
        self.player1Slot03 = CardLabel(self.centralwidget)
        self.player1Slot03.setSizePolicy(sizePolicy)
        self.player1Slot03.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot03.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot03.setFont(font)
        self.player1Slot03.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot03.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot03.setObjectName("player1Slot03")
        self.player1lLayout.addWidget(self.player1Slot03)
        self.player1Slot02 = CardLabel(self.centralwidget)
        self.player1Slot02.setSizePolicy(sizePolicy)
        self.player1Slot02.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot02.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot02.setFont(font)
        self.player1Slot02.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot02.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot02.setObjectName("player1Slot02")
        self.player1lLayout.addWidget(self.player1Slot02)
        self.player1Slot01 = CardLabel(self.centralwidget)
        self.player1Slot01.setSizePolicy(sizePolicy)
        self.player1Slot01.setMinimumSize(QtCore.QSize(48, 48))
        self.player1Slot01.setMaximumSize(QtCore.QSize(48, 48))
        self.player1Slot01.setFont(font)
        self.player1Slot01.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Slot01.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Slot01.setObjectName("player1Slot01")
        self.player1lLayout.addWidget(self.player1Slot01)
        self.gridLayoutMain.addLayout(self.player1lLayout, 3, 0, 11, 1)
        
        self.player2Layout = QtWidgets.QHBoxLayout()
        self.player2Layout.setObjectName("player2Layout")
        self.player2Slot01 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot01.setSizePolicy(sizePolicy)
        self.player2Slot01.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot01.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot01.setFont(font)
        self.player2Slot01.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot01.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot01.setObjectName("player2Slot01")
        self.player2Layout.addWidget(self.player2Slot01)
        self.player2Slot02 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot02.setSizePolicy(sizePolicy)
        self.player2Slot02.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot02.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot02.setFont(font)
        self.player2Slot02.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot02.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot02.setObjectName("player2Slot02")
        self.player2Layout.addWidget(self.player2Slot02)
        self.player2Slot03 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot03.setSizePolicy(sizePolicy)
        self.player2Slot03.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot03.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot03.setFont(font)
        self.player2Slot03.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot03.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot03.setObjectName("player2Slot03")
        self.player2Layout.addWidget(self.player2Slot03)
        self.player2Slot04 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot04.setSizePolicy(sizePolicy)
        self.player2Slot04.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot04.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot04.setFont(font)
        self.player2Slot04.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot04.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot04.setObjectName("player2Slot04")
        self.player2Layout.addWidget(self.player2Slot04)
        self.player2Slot05 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot05.setSizePolicy(sizePolicy)
        self.player2Slot05.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot05.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot05.setFont(font)
        self.player2Slot05.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot05.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot05.setObjectName("player2Slot05")
        self.player2Layout.addWidget(self.player2Slot05)
        self.player2Slot06 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot06.setSizePolicy(sizePolicy)
        self.player2Slot06.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot06.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot06.setFont(font)
        self.player2Slot06.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot06.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot06.setObjectName("player2Slot06")
        self.player2Layout.addWidget(self.player2Slot06)
        self.player2Slot07 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot07.setSizePolicy(sizePolicy)
        self.player2Slot07.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot07.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot07.setFont(font)
        self.player2Slot07.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot07.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot07.setObjectName("player2Slot07")
        self.player2Layout.addWidget(self.player2Slot07)
        self.player2Slot08 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot08.setSizePolicy(sizePolicy)
        self.player2Slot08.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot08.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot08.setFont(font)
        self.player2Slot08.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot08.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot08.setObjectName("player2Slot08")
        self.player2Layout.addWidget(self.player2Slot08)
        self.player2Slot09 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot09.setSizePolicy(sizePolicy)
        self.player2Slot09.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot09.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot09.setFont(font)
        self.player2Slot09.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot09.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot09.setObjectName("player2Slot09")
        self.player2Layout.addWidget(self.player2Slot09)
        self.player2Slot10 = QtWidgets.QLabel(self.centralwidget)
        self.player2Slot10.setSizePolicy(sizePolicy)
        self.player2Slot10.setMinimumSize(QtCore.QSize(48, 48))
        self.player2Slot10.setMaximumSize(QtCore.QSize(48, 48))
        self.player2Slot10.setFont(font)
        self.player2Slot10.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Slot10.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Slot10.setObjectName("player2Slot10")
        self.player2Layout.addWidget(self.player2Slot10)
        self.gridLayoutMain.addLayout(self.player2Layout, 3, 2, 1, 3)
        
        self.player3Layout = QtWidgets.QVBoxLayout()
        self.player3Layout.setObjectName("player3Layout")
        self.player3Slot10 = CardLabel(self.centralwidget)
        self.player3Slot10.setSizePolicy(sizePolicy)
        self.player3Slot10.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot10.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot10.setFont(font)
        self.player3Slot10.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot10.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot10.setObjectName("player3Slot10")
        self.player3Layout.addWidget(self.player3Slot10)
        self.player3Slot09 = CardLabel(self.centralwidget)
        self.player3Slot09.setSizePolicy(sizePolicy)
        self.player3Slot09.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot09.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot09.setFont(font)
        self.player3Slot09.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot09.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot09.setObjectName("player3Slot09")
        self.player3Layout.addWidget(self.player3Slot09)
        self.player3Slot08 = CardLabel(self.centralwidget)
        self.player3Slot08.setSizePolicy(sizePolicy)
        self.player3Slot08.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot08.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot08.setFont(font)
        self.player3Slot08.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot08.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot08.setObjectName("player3Slot08")
        self.player3Layout.addWidget(self.player3Slot08)
        self.player3Slot07 = CardLabel(self.centralwidget)
        self.player3Slot07.setSizePolicy(sizePolicy)
        self.player3Slot07.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot07.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot07.setFont(font)
        self.player3Slot07.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot07.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot07.setObjectName("player3Slot07")
        self.player3Layout.addWidget(self.player3Slot07)
        self.player3Slot06 = CardLabel(self.centralwidget)
        self.player3Slot06.setSizePolicy(sizePolicy)
        self.player3Slot06.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot06.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot06.setFont(font)
        self.player3Slot06.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot06.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot06.setObjectName("player3Slot06")
        self.player3Layout.addWidget(self.player3Slot06)
        self.player3Slot05 = CardLabel(self.centralwidget)
        self.player3Slot05.setSizePolicy(sizePolicy)
        self.player3Slot05.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot05.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot05.setFont(font)
        self.player3Slot05.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot05.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot05.setObjectName("player3Slot05")
        self.player3Layout.addWidget(self.player3Slot05)
        self.player3Slot04 = CardLabel(self.centralwidget)
        self.player3Slot04.setSizePolicy(sizePolicy)
        self.player3Slot04.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot04.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot04.setFont(font)
        self.player3Slot04.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot04.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot04.setObjectName("player3Slot04")
        self.player3Layout.addWidget(self.player3Slot04)
        self.player3Slot03 = CardLabel(self.centralwidget)
        self.player3Slot03.setSizePolicy(sizePolicy)
        self.player3Slot03.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot03.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot03.setFont(font)
        self.player3Slot03.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot03.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot03.setObjectName("player3Slot03")
        self.player3Layout.addWidget(self.player3Slot03)
        self.player3Slot02 = CardLabel(self.centralwidget)
        self.player3Slot02.setSizePolicy(sizePolicy)
        self.player3Slot02.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot02.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot02.setFont(font)
        self.player3Slot02.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot02.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot02.setObjectName("player3Slot02")
        self.player3Layout.addWidget(self.player3Slot02)
        self.player3Slot01 = CardLabel(self.centralwidget)
        self.player3Slot01.setSizePolicy(sizePolicy)
        self.player3Slot01.setMinimumSize(QtCore.QSize(48, 48))
        self.player3Slot01.setMaximumSize(QtCore.QSize(48, 48))
        self.player3Slot01.setFont(font)
        self.player3Slot01.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Slot01.setFrameShape(QtWidgets.QFrame.Box)
        self.player3Slot01.setObjectName("player3Slot01")
        self.player3Layout.addWidget(self.player3Slot01)
        self.gridLayoutMain.addLayout(self.player3Layout, 3, 6, 11, 1)
        
        self.player4Layout = QtWidgets.QHBoxLayout()
        self.player4Layout.setObjectName("player4Layout")
        self.player4Slot01 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot01.setSizePolicy(sizePolicy)
        self.player4Slot01.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot01.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot01.setFont(font)
        self.player4Slot01.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot01.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot01.setObjectName("player4Slot01")
        self.player4Layout.addWidget(self.player4Slot01)
        self.player4Slot02 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot02.setSizePolicy(sizePolicy)
        self.player4Slot02.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot02.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot02.setFont(font)
        self.player4Slot02.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot02.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot02.setObjectName("player4Slot02")
        self.player4Layout.addWidget(self.player4Slot02)
        self.player4Slot03 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot03.setSizePolicy(sizePolicy)
        self.player4Slot03.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot03.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot03.setFont(font)
        self.player4Slot03.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot03.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot03.setObjectName("player4Slot03")
        self.player4Layout.addWidget(self.player4Slot03)
        self.player4Slot04 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot04.setSizePolicy(sizePolicy)
        self.player4Slot04.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot04.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot04.setFont(font)
        self.player4Slot04.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot04.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot04.setObjectName("player4Slot04")
        self.player4Layout.addWidget(self.player4Slot04)
        self.player4Slot05 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot05.setSizePolicy(sizePolicy)
        self.player4Slot05.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot05.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot05.setFont(font)
        self.player4Slot05.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot05.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot05.setObjectName("player4Slot05")
        self.player4Layout.addWidget(self.player4Slot05)
        self.player4Slot06 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot06.setSizePolicy(sizePolicy)
        self.player4Slot06.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot06.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot06.setFont(font)
        self.player4Slot06.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot06.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot06.setObjectName("player4Slot06")
        self.player4Layout.addWidget(self.player4Slot06)
        self.player4Slot07 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot07.setSizePolicy(sizePolicy)
        self.player4Slot07.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot07.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot07.setFont(font)
        self.player4Slot07.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot07.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot07.setObjectName("player4Slot07")
        self.player4Layout.addWidget(self.player4Slot07)
        self.player4Slot08 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot08.setSizePolicy(sizePolicy)
        self.player4Slot08.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot08.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot08.setFont(font)
        self.player4Slot08.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot08.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot08.setObjectName("player4Slot08")
        self.player4Layout.addWidget(self.player4Slot08)
        self.player4Slot09 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot09.setSizePolicy(sizePolicy)
        self.player4Slot09.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot09.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot09.setFont(font)
        self.player4Slot09.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot09.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot09.setObjectName("player4Slot09")
        self.player4Layout.addWidget(self.player4Slot09)
        self.player4Slot10 = QtWidgets.QLabel(self.centralwidget)
        self.player4Slot10.setSizePolicy(sizePolicy)
        self.player4Slot10.setMinimumSize(QtCore.QSize(48, 48))
        self.player4Slot10.setMaximumSize(QtCore.QSize(48, 48))
        self.player4Slot10.setFont(font)
        self.player4Slot10.setAlignment(QtCore.Qt.AlignCenter)
        self.player4Slot10.setFrameShape(QtWidgets.QFrame.Box)
        self.player4Slot10.setObjectName("player4Slot10")
        self.player4Layout.addWidget(self.player4Slot10)        
        self.gridLayoutMain.addLayout(self.player4Layout, 11, 2, 1, 3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.actionHowToPlay = QtWidgets.QAction(MainWindow)
        self.actionHowToPlay.setObjectName("actionHowToPlay")
        self.actionViewHistory = QtWidgets.QAction(MainWindow)
        self.actionViewHistory.setObjectName("actionViewHistory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHelp.addAction(self.actionHowToPlay)
        self.menuHelp.addAction(self.actionViewHistory)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionExit)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.requirePlayer2.setItemText(0, _translate("MainWindow", "Easy"))
        self.requirePlayer2.setItemText(1, _translate("MainWindow", "Moderate"))
        self.requirePlayer2.setItemText(2, _translate("MainWindow", "Hard"))
        self.optionPlayer3.setItemText(0, _translate("MainWindow", "Disabled"))
        self.optionPlayer3.setItemText(1, _translate("MainWindow", "Easy"))
        self.optionPlayer3.setItemText(2, _translate("MainWindow", "Moderate"))
        self.optionPlayer3.setItemText(3, _translate("MainWindow", "Hard"))
        self.optionPlayer4.setItemText(0, _translate("MainWindow", "Disabled"))
        self.optionPlayer4.setItemText(1, _translate("MainWindow", "Play 2 sets"))
        self.optionPlayer4.setItemText(2, _translate("MainWindow", "Easy"))
        self.optionPlayer4.setItemText(3, _translate("MainWindow", "Moderate"))
        self.optionPlayer4.setItemText(4, _translate("MainWindow", "Hard"))
        self.actionButton.setText(_translate("MainWindow", "New Game"))
        self.optionView.setText(_translate("MainWindow", "Show Replacement"))
        
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHowToPlay.setText(_translate("MainWindow", "How to play"))
        self.actionViewHistory.setText(_translate("MainWindow", "View History"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

